print("#################################")
print("#                               #")
print("# Maula Muhammad Farrel Rabbani #")
print("#         2510817310008         #")
print("#                               #")
print("#################################")